
import { AggregateRoot } from '../../../shared-kernel/base-entities/aggregate-root';

export class Branch extends AggregateRoot<Branch> {
    constructor(
        public readonly id: string,
        public tenantId: string,
        public name: string,
        public address: string | null,
        public phone: string | null,
        public readonly createdAt: Date,
        public readonly updatedAt: Date,
    ) {
        super();
    }

    static create(tenantId: string, name: string, address?: string, phone?: string): Branch {
        return new Branch(
            crypto.randomUUID(), // Or let DB handle it? Standard is UUID in App or DB. 
            // Prisma usually handles default(uuid()) but for DDD we often generate ID here.
            // Let's assume ID is generated by DB or passed in. 
            // To be safe with Prisma default, we can make ID optional in create but standard in entity.
            // For now, let's assume we pass ID or rely on repo.
            // Actually, for consistency with Tenant, we might generate it. 
            // Let's proceed with Entity simply holding data for now.

            // Wait, crypto check. Node 20 has global crypto.
            // But let's stick to simple constructor.
            tenantId,
            name,
            address || null,
            phone || null,
            new Date(),
            new Date(),
        );
    }
}
