/**
 * PHASE 14G: Canonical Action Keys
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * SAP-GRADE semantic action identifiers for UI rendering.
 * SYNCED with permission-structure.ts action names.
 * 
 * RULES:
 * - UI MUST import keys from this file
 * - Hardcoded strings are FORBIDDEN
 * - Keys match backend page-state response format: GS_{ENTITY}_{ACTION}
 * 
 * ═══════════════════════════════════════════════════════════════════════════
 */

export const ACTION_KEYS = {
    // ─────────────────────────────────────────────────────────────────────────
    // Tenants Entity (Phase 14G)
    // ─────────────────────────────────────────────────────────────────────────
    TENANTS_CREATE: 'GS_TENANTS_CREATE',
    TENANTS_UPDATE: 'GS_TENANTS_UPDATE',
    TENANTS_DELETE: 'GS_TENANTS_DELETE',
    TENANTS_IMPERSONATE: 'GS_TENANTS_IMPERSONATE',
    // Granular Actions (Phase 14G Refinement)
    TENANTS_MANAGE_USERS: 'GS_TENANTS_MANAGE_USERS',
    TENANTS_MANAGE_SECURITY: 'GS_TENANTS_MANAGE_SECURITY',
    TENANTS_MANAGE_BILLING: 'GS_TENANTS_MANAGE_BILLING',
    TENANTS_MANAGE_FEATURES: 'GS_TENANTS_MANAGE_FEATURES',
    TENANTS_MANAGE_CONTRACT: 'GS_TENANTS_MANAGE_CONTRACT',
    TENANTS_VIEW_AUDIT: 'GS_TENANTS_VIEW_AUDIT',
    TENANTS_EXPORT: 'GS_TENANTS_EXPORT_TO_EXCEL',

    // ─────────────────────────────────────────────────────────────────────────
    // Users Entity - Synced with permission-structure.ts
    // ─────────────────────────────────────────────────────────────────────────
    USERS_CREATE: 'GS_USERS_CREATE',
    USERS_READ: 'GS_USERS_READ',
    USERS_UPDATE: 'GS_USERS_UPDATE',
    USERS_DELETE: 'GS_USERS_DELETE',
    USERS_EXPORT: 'GS_USERS_EXPORT_TO_EXCEL',
    USERS_ACTIVATE: 'GS_USERS_CHANGE_STATUS',
    USERS_CONNECT_TO_EMPLOYEE: 'GS_USERS_CONNECT_TO_EMPLOYEE',
    USERS_INVITE: 'GS_USERS_INVITE',
    // Row-level actions
    USERS_IMPERSONATE: 'GS_USERS_IMPERSONATE',
    USERS_SEND_INVITE: 'GS_USERS_SEND_INVITE',
    USERS_MANAGE_RESTRICTIONS: 'GS_USERS_MANAGE_RESTRICTIONS',

    // ─────────────────────────────────────────────────────────────────────────
    // Roles Entity
    // ─────────────────────────────────────────────────────────────────────────
    ROLES_CREATE: 'GS_ROLES_CREATE',
    ROLES_READ: 'GS_ROLES_READ',
    ROLES_UPDATE: 'GS_ROLES_UPDATE',
    ROLES_DELETE: 'GS_ROLES_DELETE',
    ROLES_EXPORT: 'GS_ROLES_EXPORT_TO_EXCEL',
    ROLES_SUBMIT: 'GS_ROLES_SUBMIT',
    ROLES_APPROVE: 'GS_ROLES_APPROVE',
    ROLES_REJECT: 'GS_ROLES_REJECT',

    // ─────────────────────────────────────────────────────────────────────────
    // Curators Entity - Synced with permission-structure.ts
    // ─────────────────────────────────────────────────────────────────────────
    CURATORS_CREATE: 'GS_CURATORS_CREATE',
    CURATORS_READ: 'GS_CURATORS_READ',
    CURATORS_UPDATE: 'GS_CURATORS_UPDATE',
    CURATORS_DELETE: 'GS_CURATORS_DELETE',
    CURATORS_EXPORT: 'GS_CURATORS_EXPORT_TO_EXCEL',
    CURATORS_CHANGE_STATUS: 'GS_CURATORS_CHANGE_STATUS',
    CURATORS_COPY_ID: 'GS_CURATORS_COPY_ID',

    // ─────────────────────────────────────────────────────────────────────────
    // PHASE 14H: Settings Domain - Synced with page-objects.registry.ts
    // ─────────────────────────────────────────────────────────────────────────
    SETTINGS_COMPANY_PROFILE_UPDATE: 'GS_SETTINGS_COMPANY_PROFILE_UPDATE',

    SETTINGS_SECURITY_SSO_OAUTH_CREATE: 'GS_SETTINGS_SECURITY_SSO_OAUTH_CREATE',
    SETTINGS_SECURITY_SSO_OAUTH_UPDATE: 'GS_SETTINGS_SECURITY_SSO_OAUTH_UPDATE',
    SETTINGS_SECURITY_SSO_OAUTH_DELETE: 'GS_SETTINGS_SECURITY_SSO_OAUTH_DELETE',
    SETTINGS_SECURITY_SSO_OAUTH_CHANGE_STATUS: 'GS_SETTINGS_SECURITY_SSO_OAUTH_CHANGE_STATUS',
    SETTINGS_SECURITY_SSO_OAUTH_TEST_CONNECTION: 'GS_SETTINGS_SECURITY_SSO_OAUTH_TEST_CONNECTION',
    SETTINGS_SECURITY_SSO_OAUTH_EXPORT: 'GS_SETTINGS_SECURITY_SSO_OAUTH_EXPORT_TO_EXCEL',

    SETTINGS_COMMUNICATION_EMAIL_UPDATE: 'GS_SETTINGS_COMMUNICATION_EMAIL_UPDATE',
    SETTINGS_COMMUNICATION_EMAIL_SEND_TEST: 'GS_SETTINGS_COMMUNICATION_EMAIL_SEND_TEST',
    SETTINGS_COMMUNICATION_EMAIL_CHANGE_STATUS: 'GS_SETTINGS_COMMUNICATION_EMAIL_CHANGE_STATUS',

    SETTINGS_COMMUNICATION_SMS_UPDATE: 'GS_SETTINGS_COMMUNICATION_SMS_UPDATE',
    SETTINGS_COMMUNICATION_SMS_SEND_TEST: 'GS_SETTINGS_COMMUNICATION_SMS_SEND_TEST',
    SETTINGS_COMMUNICATION_SMS_CHANGE_STATUS: 'GS_SETTINGS_COMMUNICATION_SMS_CHANGE_STATUS',

    SETTINGS_NOTIFICATION_ENGINE_CREATE: 'GS_SETTINGS_NOTIFICATION_ENGINE_CREATE',
    SETTINGS_NOTIFICATION_ENGINE_UPDATE: 'GS_SETTINGS_NOTIFICATION_ENGINE_UPDATE',
    SETTINGS_NOTIFICATION_ENGINE_DELETE: 'GS_SETTINGS_NOTIFICATION_ENGINE_DELETE',
    SETTINGS_NOTIFICATION_ENGINE_CHANGE_STATUS: 'GS_SETTINGS_NOTIFICATION_ENGINE_CHANGE_STATUS',
    SETTINGS_NOTIFICATION_ENGINE_EXPORT: 'GS_SETTINGS_NOTIFICATION_ENGINE_EXPORT_TO_EXCEL',
    SETTINGS_NOTIFICATION_ENGINE_COPY: 'GS_SETTINGS_NOTIFICATION_ENGINE_COPY_JSON',

    // ─────────────────────────────────────────────────────────────────────────
    // PHASE 14H: Billing Domain - Synced with page-objects.registry.ts
    // ─────────────────────────────────────────────────────────────────────────
    BILLING_PLANS_CREATE: 'GS_BILLING_PLANS_CREATE',
    BILLING_PLANS_UPDATE: 'GS_BILLING_PLANS_UPDATE',
    BILLING_PLANS_DELETE: 'GS_BILLING_PLANS_DELETE',
    BILLING_PLANS_CHANGE_STATUS: 'GS_BILLING_PLANS_CHANGE_STATUS',
    BILLING_PLANS_EXPORT: 'GS_BILLING_PLANS_EXPORT',

    BILLING_MARKETPLACE_CREATE: 'GS_BILLING_MARKETPLACE_CREATE',
    BILLING_MARKETPLACE_UPDATE: 'GS_BILLING_MARKETPLACE_UPDATE',
    BILLING_MARKETPLACE_DELETE: 'GS_BILLING_MARKETPLACE_DELETE',
    BILLING_MARKETPLACE_CHANGE_STATUS: 'GS_BILLING_MARKETPLACE_CHANGE_STATUS',
    BILLING_MARKETPLACE_EXPORT: 'GS_BILLING_MARKETPLACE_EXPORT',

    BILLING_PACKAGES_CREATE: 'GS_BILLING_PACKAGES_CREATE',
    BILLING_PACKAGES_UPDATE: 'GS_BILLING_PACKAGES_UPDATE',
    BILLING_PACKAGES_DELETE: 'GS_BILLING_PACKAGES_DELETE',
    BILLING_PACKAGES_CHANGE_STATUS: 'GS_BILLING_PACKAGES_CHANGE_STATUS',
    BILLING_PACKAGES_EXPORT: 'GS_BILLING_PACKAGES_EXPORT',

    LICENSES_CHANGE_PLAN: 'GS_LICENSES_CHANGE_PLAN',
    LICENSES_MANAGE_SEATS: 'GS_LICENSES_MANAGE_SEATS',
    LICENSES_CANCEL: 'GS_LICENSES_CANCEL',
    LICENSES_VIEW_AUDIT: 'GS_LICENSES_VIEW_AUDIT',

    INVOICES_READ: 'GS_INVOICES_READ',
    INVOICES_DOWNLOAD: 'GS_INVOICES_DOWNLOAD',
    INVOICES_RESEND: 'GS_INVOICES_RESEND',
    INVOICES_VOID: 'GS_INVOICES_VOID',
    INVOICES_PAY: 'GS_INVOICES_PAY',
    INVOICES_EXPORT: 'GS_INVOICES_EXPORT_TO_EXCEL',
} as const;

// Type for action keys
export type ActionKey = typeof ACTION_KEYS[keyof typeof ACTION_KEYS];

// PHASE 14H: ActionsMap is now dynamic - see usePageState.ts
// This type is kept for backward compatibility
export type ActionsMap = Record<ActionKey, boolean>;

