
import { Injectable, Inject } from '@nestjs/common';
import type { IStorageProvider } from '../domain/storage.interface';
import { PrismaFileRepository } from '../infrastructure/persistence/prisma-file.repository';
import { FileEntity } from '../domain/file.entity';

@Injectable()
export class FilesUseCase {
    constructor(
        @Inject('IStorageProvider')
        private readonly storageProvider: IStorageProvider,
        private readonly fileRepository: PrismaFileRepository
    ) { }

    async uploadFile(file: Express.Multer.File, userId: string): Promise<FileEntity> {
        const filename = `${Date.now()}-${file.originalname}`;
        const { path, publicUrl } = await this.storageProvider.upload(file, filename);

        const fileEntity = new FileEntity(
            undefined as any, // ID generated by DB
            file.originalname,
            filename,
            file.mimetype,
            file.size,
            path,
            publicUrl,
            userId,
            new Date()
        );

        return this.fileRepository.create(fileEntity);
    }
}
