
import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../../../prisma.service';
import { FileEntity } from '../../domain/file.entity'; // Rename? File is reserved.

@Injectable()
export class PrismaFileRepository { // Should implement interface but keeping simple for now
    constructor(private prisma: PrismaService) { }

    async create(file: FileEntity): Promise<FileEntity> {
        const created = await this.prisma.file.create({
            data: {
                id: file.id, // usually generated by Prisma default? But entity has it.
                // Let's rely on Prisma generation usually or pass it.
                // If ID is undefined in Entity constructor, fine.
                // I will let Prisma generate ID.
                originalName: file.originalName,
                filename: file.filename,
                mimeType: file.mimeType,
                size: file.size,
                path: file.path,
                publicUrl: file.publicUrl,
                uploadedBy: file.uploadedBy,
                module: 'GENERAL',
                usage: 'OTHER'
            }
        });
        return this.mapToDomain(created);
    }

    private mapToDomain(row: any): FileEntity {
        return new FileEntity(
            row.id,
            row.originalName,
            row.filename,
            row.mimeType,
            row.size,
            row.path,
            row.publicUrl,
            row.uploadedBy,
            row.createdAt
        );
    }
}
